tv_schedule/urls.py
from django.urls import path
from . import views

app_name = 'tv_schedule'

urlpatterns = [
    path('turn-on/', views.turn_on_tv, name='turn_on_tv'),
    path('turn-off/', views.turn_off_tv, name='turn_off_tv'),
]

tv_schedule/models.py
from django.db import models


class TVSchedule(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    status = models.BooleanField(default=False)

tv_schedule/forms.py
from django import forms
from .models import TVSchedule


class TVScheduleForm(forms.ModelForm):
    class Meta:
        model = TVSchedule
        fields = ['start_time', 'end_time']

tv_schedule/views.py
from django.shortcuts import render
from .models import TVSchedule


def turn_on_tv(request):
    tv_schedule = TVSchedule.objects.get(request)
    tv_schedule.status = True
    tv_schedule.save()
    return render(request, 'tv_schedule/list.html')


def turn_off_tv(request):
    tv_schedule = TVSchedule.objects.get(request)
    tv_schedule.status = False
    tv_schedule.save()
    return render(request, 'tv_schedule/list.html')

tv_schedule/templates/tv_schedule/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}TV Schedule{% endblock %}</title>
</head>

<body>
    <nav>
        <ul>
            <li><a href="{% url 'turn_on_tv' %}">Turn TV on</a></li>
            <li><a href="{% url 'turn_off_tv' %}">Turn TV off</a></li>
        </ul>
    </nav>
    {% block content %}{% endblock %}
</body>

</html>

tv_schedule/templates/tv_schedule/list.html
{% extends 'base.html' %}

{% block content %}
<h2>TV Schedule</h2>
<table>
    <thead>
        <tr>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for schedule in tv_schedules %}
        <tr>
            <td>{{ schedule.start_time }}</td>
            <td>{{ schedule.end_time }}</td>
            <td>{% if schedule.status %}On{% else %}Off{% endif %}</td>
            <td>
                {% if not schedule.status %}
                <a href="{% url 'tv_schedule:turn_on_tv' pk=schedule.pk %}">Turn On</a>
                {% else %}
                <a href="{% url 'tv_schedule:turn_off_tv' pk=schedule.pk %}">Turn Off</a>
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No TV schedules found.</td>
        </tr>
        {%}